# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.define :servidorhaproxy do |servidorhaproxy|

		servidorhaproxy.vm.box = "bento/ubuntu-18.04"
		servidorhaproxy.vm.network :private_network, ip: "192.168.100.10"
		servidorhaproxy.vm.provision "shell", path: "haproxy.sh"
		servidorhaproxy.vm.hostname = "servidorhaproxy"

	end

	config.vm.define :web1 do |web1|

		web1.vm.box = "bento/ubuntu-18.04"
		web1.vm.network :private_network, ip: "192.168.100.2"
		web1.vm.provision "shell", path: "provisioner.sh"
		web1.vm.hostname = "web1"

	end

	config.vm.define :web2 do |web2|

		web2.vm.box = "bento/ubuntu-18.04"
		web2.vm.network :private_network, ip: "192.168.100.3"
		web2.vm.provision "shell", path: "provisioner2.sh"
		web2.vm.hostname = "web2"

	end

	config.vm.define :web3 do |web3|

		web3.vm.box = "bento/ubuntu-18.04"
		web3.vm.network :private_network, ip: "192.168.100.4"
		web3.vm.provision "shell", path: "provisioner3.sh"
		web3.vm.hostname = "web3"

	end

end