# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

if Vagrant.has_plugin? "vagrant-vbguest"
	config.vbguest.no_install = true
	config.vbguest.auto_update = false
	config.vbguest.no_remote = true
end

config.vm.define :cliente do |cliente|
	cliente.vm.box = "bento/ubuntu-20.04"
	cliente.vm.network :private_network, ip: "192.168.56.4"
	cliente.vm.hostname = "cliente"
end

config.vm.define :servidor do |servidor|
	servidor.vm.box = "bento/ubuntu-20.04"
	servidor.vm.network :private_network, ip: "192.168.56.5"
	servidor.vm.hostname = "servidor"
end

end